import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // — Obsidian Ledger Design System —
        "tertiary-fixed": "#6ffbbe",
        "on-surface": "#e4e1e9",
        outline: "#a78a8a",
        background: "#131318",
        "primary-container": "#800020",
        "primary-fixed-dim": "#ffb3b5",
        "tertiary-container": "#00472f",
        "error-container": "#93000a",
        "surface-tint": "#ffb3b5",
        "on-background": "#e4e1e9",
        "on-primary-fixed": "#40000b",
        "secondary-fixed-dim": "#00dbe9",
        "secondary-fixed": "#7df4ff",
        "outline-variant": "#584141",
        primary: {
          DEFAULT: "#ffb3b5",
          foreground: "#680018",
        },
        secondary: {
          DEFAULT: "#d3fbff",
          foreground: "#00363a",
        },
        "inverse-surface": "#e4e1e9",
        "surface-container": "#1f1f25",
        "on-tertiary": "#003824",
        "on-secondary-container": "#00686f",
        tertiary: "#4edea3",
        "surface-bright": "#39383e",
        error: "#ffb4ab",
        "surface-dim": "#131318",
        "inverse-primary": "#af2b3e",
        "on-secondary-fixed-variant": "#004f54",
        "primary-fixed": "#ffdada",
        "on-secondary": "#00363a",
        "surface-variant": "#35343a",
        "on-surface-variant": "#e0bfbf",
        "on-primary": "#680018",
        "on-primary-fixed-variant": "#8e0f28",
        "on-tertiary-container": "#20bf86",
        "on-primary-container": "#ff828a",
        "on-error": "#690005",
        "inverse-on-surface": "#303036",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-container": "#00eefc",
        "surface-container-high": "#2a292f",
        "surface-container-low": "#1b1b20",
        surface: "#131318",
        "on-secondary-fixed": "#002022",
        "surface-container-highest": "#35343a",
        "on-tertiary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0e0e13",
        "tertiary-fixed-dim": "#4edea3",

        // Legacy compat
        "primary-dark": "#4A0404",
        "background-dark": "#0B0E14",
        "surface-dark": "#161b22",
        "neon-cyan": "#00F0FF",
        midnight: "#111625",
        "glass-border": "rgba(255, 255, 255, 0.08)",
        "glass-surface": "rgba(255, 255, 255, 0.03)",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["'Space Grotesk'", "sans-serif"],
        display: ["'Space Grotesk'", "sans-serif"],
        body: ["'Space Grotesk'", "sans-serif"],
        label: ["'Inter'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        sans: ["'Space Grotesk'", "sans-serif"],
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
