import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // — Reflex Cream & Orange Design System —
        background: "#F5F0EB",
        foreground: "#1A1A1A",
        cream: {
          50: "#FAF8F5",
          100: "#F5F0EB",
          200: "#EDE8E3",
          300: "#D1CBC5",
          400: "#B0AAA4",
          500: "#8F8983",
        },
        orange: {
          DEFAULT: "#FF6B00",
          50: "#FFF5EB",
          100: "#FFE5CC",
          200: "#FFCC99",
          300: "#FFB366",
          400: "#FF8A33",
          500: "#FF6B00",
          600: "#E55E00",
          700: "#CC5300",
          800: "#994000",
          900: "#662A00",
        },
        "on-surface": "#1A1A1A",
        "on-surface-muted": "#71717A",
        primary: {
          DEFAULT: "#FF6B00",
          foreground: "#FFFFFF",
        },
        secondary: {
          DEFAULT: "#F5F0EB",
          foreground: "#1A1A1A",
        },
        surface: {
          DEFAULT: "#FFFFFF",
          muted: "#FAF8F5",
          container: "#F5F0EB",
        },
        // Chart / Category colors
        "chart-blue": "#3B82F6",
        "chart-emerald": "#10B981",
        "chart-amber": "#F59E0B",
        "chart-red": "#EF4444",
        "chart-indigo": "#6366F1",

        // Legacy compat (keep so dashboard pages don't break)
        "primary-container": "#FF6B00",
        "primary-fixed-dim": "#FF8A33",
        "surface-tint": "#FF6B00",
        "on-background": "#1A1A1A",
        "surface-container": "#EDE8E3",
        "surface-bright": "#FFFFFF",
        "surface-dim": "#F5F0EB",
        "surface-container-high": "#FAF8F5",
        "surface-container-low": "#FFFFFF",
        "surface-container-highest": "#EDE8E3",
        "surface-container-lowest": "#FFFFFF",
        "outline-variant": "#D1CBC5",
        "inverse-surface": "#1A1A1A",
        "inverse-on-surface": "#FFFFFF",
        "inverse-primary": "#FF8A33",
        tertiary: "#10B981",
        "tertiary-container": "#D1FAE5",
        "on-tertiary-container": "#065F46",
        error: "#EF4444",
        "error-container": "#FEE2E2",
        "on-error-container": "#991B1B",
        "on-primary-container": "#FFFFFF",
        "on-secondary-container": "#1A1A1A",
        "on-secondary-fixed-variant": "#71717A",
        "secondary-container": "#EDE8E3",
        "on-primary": "#FFFFFF",
        "on-secondary": "#1A1A1A",
        "on-tertiary": "#FFFFFF",
        "on-error": "#FFFFFF",
        "glass-border": "rgba(0, 0, 0, 0.06)",
        "glass-surface": "rgba(255, 255, 255, 0.7)",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "2.5rem",
        "3xl": "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["'Inter'", "sans-serif"],
        display: ["'Inter'", "sans-serif"],
        body: ["'Inter'", "sans-serif"],
        label: ["'Inter'", "sans-serif"],
        mono: ["'Inter'", "sans-serif"],
        sans: ["'Inter'", "sans-serif"],
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "slide-up": "slide-up 0.6s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
      },
      boxShadow: {
        glass: "0 4px 30px rgba(0, 0, 0, 0.04)",
        "glass-lg": "0 8px 40px rgba(0, 0, 0, 0.06)",
        "orange-sm": "0 4px 14px rgba(255, 107, 0, 0.15)",
        "orange-md": "0 8px 25px rgba(255, 107, 0, 0.2)",
        "orange-lg": "0 12px 40px rgba(255, 107, 0, 0.25)",
        card: "0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)",
        "card-hover": "0 4px 20px rgba(0,0,0,0.08)",
      },
    },
  },
  plugins: [],
};
export default config;
